use std::io::Write;

use anyhow::{Context, Result};
use globset::{GlobBuilder, GlobSet, GlobSetBuilder};
use serde::{Deserialize, Serialize};

use crate::Report;

/// Analysis/CI settings only; input and output paths stay explicit CLI arguments.
#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase", deny_unknown_fields)]
pub struct Config {
    pub include: Vec<String>,
    pub exclude: Vec<String>,
    pub compression: bool,
    pub budgets: Budgets,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase", deny_unknown_fields)]
pub struct Budgets {
    pub max_bytes: Option<usize>,
    pub max_unobserved_bytes: Option<usize>,
    pub max_unmeasured_bytes: Option<usize>,
    pub max_gzip_bytes: Option<usize>,
    pub max_brotli_bytes: Option<usize>,
}

impl Budgets {
    pub fn check(&self, report: &Report) -> Vec<String> {
        let compressed = report.compression.as_ref();
        let mut failures = Vec::new();
        if self.max_unobserved_bytes.is_some()
            && report.totals.bytes == report.totals.unmeasured_bytes
        {
            failures.push("unobserved bytes: cannot check budget without measured coverage for selected bundles".into());
        }
        for (label, limit, value) in [
            ("generated bytes", self.max_bytes, Some(report.totals.bytes)),
            (
                "unobserved bytes",
                self.max_unobserved_bytes,
                Some(report.totals.unobserved_bytes),
            ),
            (
                "unmeasured bytes",
                self.max_unmeasured_bytes,
                Some(report.totals.unmeasured_bytes),
            ),
            (
                "gzip bytes",
                self.max_gzip_bytes,
                compressed.map(|c| c.gzip_bytes),
            ),
            (
                "Brotli bytes",
                self.max_brotli_bytes,
                compressed.map(|c| c.brotli_bytes),
            ),
        ] {
            if let Some(limit) = limit {
                match value {
                    Some(value) if value > limit => {
                        failures.push(format!("{label}: {value} exceeds budget {limit}"))
                    }
                    None => {
                        failures.push(format!("{label}: cannot check budget without compression"))
                    }
                    _ => {}
                }
            }
        }
        failures
    }
}

pub fn globs(patterns: &[String]) -> Result<GlobSet> {
    let mut builder = GlobSetBuilder::new();
    for pattern in patterns {
        builder.add(
            GlobBuilder::new(pattern)
                .literal_separator(true)
                .build()
                .with_context(|| format!("invalid bundle glob {pattern:?}"))?,
        );
    }
    Ok(builder.build()?)
}

#[derive(Debug, Clone, Default, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CompressedSizes {
    /// Independent file compression, gzip level 6 and Brotli quality 5 / lgwin 22.
    pub gzip_bytes: usize,
    pub brotli_bytes: usize,
}

impl CompressedSizes {
    pub(crate) fn add(&mut self, other: &Self) {
        self.gzip_bytes += other.gzip_bytes;
        self.brotli_bytes += other.brotli_bytes;
    }
}

pub fn compress(data: &[u8]) -> Result<CompressedSizes> {
    let (gzip, brotli) = compressed_streams(data)?;
    Ok(CompressedSizes {
        gzip_bytes: gzip.len(),
        brotli_bytes: brotli.len(),
    })
}

pub(crate) fn gzip(data: &[u8]) -> Result<Vec<u8>> {
    let mut gzip = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::new(6));
    gzip.write_all(data)?;
    Ok(gzip.finish()?)
}

fn compressed_streams(data: &[u8]) -> Result<(Vec<u8>, Vec<u8>)> {
    let gzip = gzip(data)?;
    let mut encoded = Vec::new();
    {
        let mut brotli = brotli::CompressorWriter::new(&mut encoded, 4096, 5, 22);
        brotli.write_all(data)?;
    }
    Ok((gzip, encoded))
}

pub fn markdown(report: &Report) -> String {
    let mut out = format!(
        "# coldpath\n\nGenerated UTF-8 bytes: **{}** across {} selected bundles.\n\n| Observed | Unobserved | Unmeasured |\n| ---: | ---: | ---: |\n| {} B | {} B | {} B |\n\nUnobserved means not executed during the supplied scenarios, not safe to delete.\n",
        report.totals.bytes,
        report.bundles.len(),
        report.totals.observed_bytes,
        report.totals.unobserved_bytes,
        report.totals.unmeasured_bytes
    );
    if let Some(c) = &report.compression {
        out.push_str(&format!("\nSum of independently compressed bundles: gzip (level 6) **{} B**, Brotli (quality 5, lgwin 22) **{} B**. These are not estimates of removable bytes or actual server encoding.\n", c.gzip_bytes, c.brotli_bytes));
    }
    out.push_str(&format!("\n{} bundles excluded by CLI/config filters; totals and budgets use selected bundles only.\n\n| Package | Generated B | Unobserved B | Unmeasured B |\n| --- | ---: | ---: | ---: |\n", report.excluded_bundles.len()));
    for row in report.packages.iter().take(20) {
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            escape_markdown(&row.package),
            row.counts.bytes,
            row.counts.unobserved_bytes,
            row.counts.unmeasured_bytes
        ));
    }
    for scenario in &report.scenario_reports {
        out.push_str(&format!(
            "\n## Scenario: {}\n\n{} B observed · {} B unobserved · {} B unmeasured.\n",
            escape_markdown(&scenario.scenario),
            scenario.totals.observed_bytes,
            scenario.totals.unobserved_bytes,
            scenario.totals.unmeasured_bytes
        ));
        if !scenario.interaction_candidates.is_empty() {
            out.push_str("\nCompared with the initial scenario. Interaction-only ranges are candidates for investigation; they do not prove loading time or removable bytes.\n\n| Source | Interaction only B (initial measured) | Later observed B (initial unmeasured) |\n| --- | ---: | ---: |\n");
            for row in scenario.interaction_candidates.iter().take(20) {
                out.push_str(&format!(
                    "| {} | {} | {} |\n",
                    escape_markdown(&row.source),
                    row.interaction_only_bytes,
                    row.initial_unmeasured_observed_bytes
                ));
            }
        }
    }
    if !report.recommendations.is_empty() {
        out.push_str("\n## Review actions\n\nCompressed figures are isolated-fragment estimates, not additive transfer savings. Rebuild after changes to measure savings.\n\n| Source | Scenario | Action | Candidate B | Estimated gzip B | Evidence |\n| --- | --- | --- | ---: | ---: | --- |\n");
        for row in report.recommendations.iter().take(20) {
            let evidence = row
                .import_path
                .as_ref()
                .map(|p| {
                    p.edges
                        .iter()
                        .map(|e| {
                            let loc = e
                                .location
                                .as_ref()
                                .map(|l| format!(":{}:{}", l.line, l.column))
                                .unwrap_or_default();
                            format!("{}{loc} → {} ({:?})", e.from, e.to, e.kind)
                        })
                        .collect::<Vec<_>>()
                        .join("; ")
                })
                .unwrap_or_default();
            out.push_str(&format!(
                "| {} | {} | {} | {} | {} | {} |\n",
                escape_markdown(&row.source),
                escape_markdown(row.scenario.as_deref().unwrap_or("all")),
                row.kind,
                row.bytes,
                row.estimated_compression
                    .as_ref()
                    .map(|c| c.gzip_bytes.to_string())
                    .unwrap_or_else(|| "—".into()),
                escape_markdown(&format!("{} {}", row.explanation, evidence))
            ));
        }
    }
    if let Some(comparison) = &report.baseline {
        out.push_str(&format!("\n## Change from baseline\n\nGenerated bytes: **{:+} B**. Source identities aggregate all selected bundles.\n", comparison.totals.delta.bytes));
        changes_markdown(&mut out, "Packages", &comparison.packages);
        changes_markdown(&mut out, "Sources", &comparison.sources);
        for scenario in &comparison.scenarios {
            out.push_str(&format!("\n### Scenario change: {}\n\nObserved: {:+} B · unobserved: {:+} B · unmeasured: {:+} B.\n",
                escape_markdown(&scenario.scenario), scenario.totals.delta.observed_bytes,
                scenario.totals.delta.unobserved_bytes, scenario.totals.delta.unmeasured_bytes));
            changes_markdown(&mut out, "Sources", &scenario.sources);
        }
        if let Some(cpu) = &comparison.cpu {
            cpu_changes_markdown(&mut out, cpu);
        }
        for warning in &comparison.warnings {
            out.push_str(&format!("\n- {}\n", escape_markdown(warning)));
        }
    }
    if let Some(cpu) = &report.cpu {
        out.push_str(&format!("\n## CPU self time\n\nSampled CPU profiles, kept apart from byte counts. Each value is the median over a scenario's runs with its interquartile range; each window lists its 10 largest sources and 5 largest bundle top levels, and the JSON report has every row. Below {} self samples per run a row is insufficient: its value is unreliable, and few samples do not mean low cost. Code a minifier inlined counts toward the function it was inlined into.\n", cpu.min_samples));
        for scenario in &cpu.scenarios {
            for window in &scenario.windows {
                out.push_str(&format!(
                    "\n### CPU: {}, {} window\n\n{} runs; median window {} ms.\n\n| Source | Median ms | Q1 to Q3 ms | Samples per run | Status |\n| --- | ---: | ---: | ---: | --- |\n",
                    escape_markdown(&scenario.scenario),
                    window.window,
                    scenario.runs,
                    milliseconds(window.median_duration_us)
                ));
                for row in window.sources.iter().take(10) {
                    cpu_row(&mut out, &escape_markdown(&row.source), &row.cost);
                }
                for row in window.top_level.iter().take(5) {
                    cpu_row(
                        &mut out,
                        &format!("Top level of {}", escape_markdown(&row.path)),
                        &row.cost,
                    );
                }
                for row in &window.other {
                    cpu_row(&mut out, &escape_markdown(&row.name), &row.cost);
                }
            }
        }
    }
    out.push_str(&format!("\n{} analysis warnings.\n", report.warnings.len()));
    for failure in &report.budget_failures {
        out.push_str(&format!(
            "\n- Budget failed: {}\n",
            escape_markdown(failure)
        ));
    }
    out
}

fn milliseconds(us: f64) -> String {
    format!("{:.2}", us / 1000.0)
}

fn cpu_row(out: &mut String, name: &str, cost: &crate::cpu::Cost) {
    out.push_str(&format!(
        "| {name} | {} | {} to {} | {} | {} |\n",
        milliseconds(cost.median_us),
        milliseconds(cost.q1_us),
        milliseconds(cost.q3_us),
        cost.median_samples,
        match cost.status {
            crate::cpu::CpuStatus::Measured => "measured",
            crate::cpu::CpuStatus::Insufficient => "insufficient",
        }
    ));
}

fn cpu_changes_markdown(out: &mut String, cpu: &crate::cpu::CpuComparison) {
    let count = |change: &str| {
        cpu.sources
            .iter()
            .filter(|row| row.change == change)
            .count()
    };
    out.push_str(&format!(
        "\n### CPU change from baseline\n\n{} regressed, {} improved, {} unchanged, {} inconclusive. Per source and window, a Mann-Whitney U test over per-run self time, Holm-adjusted across {} compared rows: a change needs an adjusted p-value below {} and a Hodges-Lehmann shift of at least {}% of the baseline median. Rows with insufficient samples in either report are inconclusive, not unchanged.\n",
        count("regressed"),
        count("improved"),
        count("unchanged"),
        count("inconclusive"),
        cpu.compared,
        cpu.alpha,
        cpu.min_effect * 100.0
    ));
    let side = |summary: &Option<crate::cpu::CostSummary>| match summary {
        Some(s) => format!(
            "{} ({} samples{})",
            milliseconds(s.median_us),
            s.median_samples,
            if s.status == crate::cpu::CpuStatus::Measured {
                ""
            } else {
                ", insufficient"
            }
        ),
        None => "not loaded".into(),
    };
    let measured = |summary: &Option<crate::cpu::CostSummary>| {
        summary
            .as_ref()
            .is_some_and(|s| s.status == crate::cpu::CpuStatus::Measured)
    };
    let rows = cpu
        .sources
        .iter()
        .filter(|row| {
            matches!(row.change, "regressed" | "improved")
                || (row.change == "inconclusive" && (measured(&row.before) || measured(&row.after)))
        })
        .take(20)
        .collect::<Vec<_>>();
    if rows.is_empty() {
        return;
    }
    out.push_str("\n| Scenario | Window | Source | Change | Before ms | After ms | Shift | Adjusted p |\n| --- | --- | --- | --- | ---: | ---: | ---: | ---: |\n");
    for row in rows {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} | {} |\n",
            escape_markdown(&row.scenario),
            row.window,
            escape_markdown(&row.source),
            row.change,
            side(&row.before),
            side(&row.after),
            match (row.shift_us, row.relative_shift) {
                (Some(shift), Some(relative)) =>
                    format!("{:+.2} ms ({:+.0}%)", shift / 1000.0, relative * 100.0),
                _ => "-".into(),
            },
            row.adjusted_p_value
                .map_or_else(|| "-".into(), |p| format!("{p:.2e}"))
        ));
    }
}

fn changes_markdown(out: &mut String, label: &str, rows: &[crate::baseline::Change]) {
    out.push_str(&format!("\n{label}\n\n| Name | Change | Before B | After B | Δ B | Δ unobserved B |\n| --- | --- | ---: | ---: | ---: | ---: |\n"));
    for row in rows.iter().filter(|row| row.change != "unchanged").take(20) {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {:+} | {:+} |\n",
            escape_markdown(&row.name),
            row.change,
            row.before.bytes,
            row.after.bytes,
            row.delta.bytes,
            row.delta.unobserved_bytes
        ));
    }
}

fn escape_markdown(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('|', "&#124;")
        .replace(['\r', '\n'], " ")
        .replace('`', "&#96;")
        .replace('[', "&#91;")
        .replace(']', "&#93;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read;

    #[test]
    fn compressed_streams_round_trip_and_report_actual_lengths() {
        for data in [
            Vec::new(),
            "한🔥".repeat(100).into_bytes(),
            include_bytes!("../examples/recorded/entry.js").to_vec(),
        ] {
            let (gzip, brotli) = compressed_streams(&data).unwrap();
            let mut inflated = Vec::new();
            flate2::read::GzDecoder::new(gzip.as_slice())
                .read_to_end(&mut inflated)
                .unwrap();
            assert_eq!(inflated, data);
            inflated.clear();
            brotli::Decompressor::new(brotli.as_slice(), 4096)
                .read_to_end(&mut inflated)
                .unwrap();
            assert_eq!(inflated, data);
            let sizes = compress(&data).unwrap();
            assert_eq!(sizes.gzip_bytes, gzip.len());
            assert_eq!(sizes.brotli_bytes, brotli.len());
        }
    }
}
