pub mod annotations;
pub mod attribution;
pub mod baseline;
pub mod ci;
pub mod coverage;
pub mod cpu;
pub mod evidence;
pub mod graph;
pub mod input;
pub mod maps;
pub mod metadata;
pub mod recommendations;
pub mod report;
pub mod scenario;
pub mod selection;
mod source_path;
pub mod text;

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, ensure};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use attribution::{IndexedSegment, IndexedSource, UNMAPPED};
use coverage::Interval;
use text::TextIndex;

#[derive(Debug, Default, Clone, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Counts {
    pub bytes: usize,
    pub observed_bytes: usize,
    pub unobserved_bytes: usize,
    pub unmeasured_bytes: usize,
}

impl Counts {
    fn add(&mut self, other: &Self) {
        self.bytes += other.bytes;
        self.observed_bytes += other.observed_bytes;
        self.unobserved_bytes += other.unobserved_bytes;
        self.unmeasured_bytes += other.unmeasured_bytes;
    }
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceRow {
    pub source: String,
    pub package: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_compression: Option<ci::CompressedSizes>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<annotations::SourceLabel>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duplicates: Option<Duplicates>,
    #[serde(flatten)]
    pub counts: Counts,
}

/// A source shipped in more than one bundle. Independent of coverage: a copy can be needed and executed.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Duplicates {
    pub bundles: usize,
    /// Bytes of every copy except the largest one.
    pub extra_bytes: usize,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PackageRow {
    pub package: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_compression: Option<ci::CompressedSizes>,
    #[serde(flatten)]
    pub counts: Counts,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BundleRow {
    pub path: String,
    pub sha256: String,
    pub source_map_sha256: Option<String>,
    pub utf16_units: usize,
    pub observed_utf16_units: Option<usize>,
    pub mapped_bytes: usize,
    pub verification: Vec<input::Verification>,
    #[serde(skip_serializing_if = "String::is_empty")]
    pub generated_source: String,
    pub sources: Vec<BundleSource>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub spans: Vec<Span>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    pub scenario_spans: BTreeMap<String, Vec<Span>>,
    pub compression: Option<ci::CompressedSizes>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub loading: Option<annotations::Loading>,
    #[serde(skip_serializing_if = "is_zero")]
    pub rejected_mappings: usize,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub mapping_diagnostics: Vec<MappingDiagnostic>,
    /// Diagnostics dropped from summary output; `rejectedMappings` stays exact.
    #[serde(skip_serializing_if = "is_zero")]
    pub omitted_mapping_diagnostics: usize,
    #[serde(flatten)]
    pub counts: Counts,
    /// The source map file this bundle was attributed with; evidence excerpts copy it.
    #[serde(skip)]
    pub source_map_path: Option<PathBuf>,
}

/// A source-map mapping skipped during attribution, with enough context to inspect it.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MappingDiagnostic {
    pub reason: attribution::RejectionReason,
    #[serde(flatten)]
    pub mapping: MappingRef,
    /// Nearest valid mappings on the same generated line.
    pub previous: Option<MappingRef>,
    pub next: Option<MappingRef>,
    /// Generated bytes whose attribution may differ had the mapping been usable.
    /// An inspection region, not a proven byte error.
    pub inspect_region: Region,
    /// Current source assignments inside `inspect_region`.
    pub assignments: Vec<Assignment>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MappingRef {
    /// Zero-based line and UTF-16 column in the generated file.
    pub generated_line: u32,
    pub generated_column: u32,
    pub source: String,
    pub original: Option<attribution::OriginalPosition>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Region {
    pub start: usize,
    pub end: usize,
    pub start_utf16: usize,
    pub end_utf16: usize,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Assignment {
    pub start: usize,
    pub end: usize,
    pub source: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BundleSource {
    pub source: String,
    pub package: String,
    pub content: Option<String>,
    pub first_observed: Vec<scenario::FirstObserved>,
    pub estimated_compression: Option<ci::CompressedSizes>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<annotations::SourceLabel>,
    /// Rejected mappings naming or assigning this source, including omitted diagnostics.
    #[serde(skip_serializing_if = "is_zero")]
    pub rejected_mappings: usize,
    /// Indices into the parent bundle's `mappingDiagnostics` naming or assigning this source.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub mapping_diagnostics: Vec<usize>,
    #[serde(flatten)]
    pub counts: Counts,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Status {
    Observed,
    Unobserved,
    Unmeasured,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Span {
    /// Half-open generated UTF-8 byte offsets.
    pub start: usize,
    pub end: usize,
    /// Half-open generated UTF-16 offsets for JavaScript string slicing.
    pub start_utf16: usize,
    pub end_utf16: usize,
    /// Index into the parent bundle's sources array.
    pub source: usize,
    pub status: Status,
    /// Zero-based source-map anchor, not a recovered original coverage range.
    pub original: Option<attribution::OriginalPosition>,
}

#[derive(Debug)]
pub struct AnalyzeOptions {
    /// Named coverage scenario used to identify interaction-only execution.
    pub initial_scenario: Option<String>,
    /// Explicit first-observation ordering; default is coverage input order.
    pub scenario_order: Vec<String>,
    pub source_compression: bool,
    /// Explicit paths relative to the analysis root; None scans the directory.
    pub files: Option<Vec<PathBuf>>,
    pub input: input::InputOptions,
    pub maps: BTreeMap<String, PathBuf>,
    pub include: Vec<String>,
    pub exclude: Vec<String>,
    pub compression: bool,
    pub details: bool,
    /// `coldpath profile` files; CPU results stay apart from byte metrics.
    pub profiles: Vec<PathBuf>,
}

impl Default for AnalyzeOptions {
    fn default() -> Self {
        Self {
            initial_scenario: None,
            scenario_order: Vec::new(),
            source_compression: false,
            files: None,
            input: Default::default(),
            maps: Default::default(),
            include: Vec::new(),
            exclude: Vec::new(),
            compression: false,
            details: true,
            profiles: Vec::new(),
        }
    }
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Report {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baseline: Option<baseline::Comparison>,
    pub schema_version: u32,
    pub details: bool,
    pub metric: &'static str,
    pub attribution: &'static str,
    pub scenarios: Vec<String>,
    pub initial_scenario: Option<String>,
    pub scenario_reports: Vec<scenario::ScenarioReport>,
    pub source_paths: &'static str,
    pub totals: Counts,
    pub bundles: Vec<BundleRow>,
    pub sources: Vec<SourceRow>,
    pub packages: Vec<PackageRow>,
    pub warnings: Vec<String>,
    /// What the collector reported about the recorded page state: aborted origins and
    /// tolerated page errors. The numbers describe that state.
    pub recording_warnings: Vec<String>,
    pub excluded_bundles: Vec<String>,
    pub include: Vec<String>,
    pub exclude: Vec<String>,
    pub compression: Option<ci::CompressedSizes>,
    pub budget_failures: Vec<String>,
    pub compression_settings: Option<&'static str>,
    pub source_compression_method: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub import_paths: Option<Vec<metadata::ImportPath>>,
    pub recommendations: Vec<recommendations::Recommendation>,
    /// Present only with profiles.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu: Option<cpu::CpuReport>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label_generator: Option<annotations::LabelGenerator>,
    /// Local files this analysis read: bundles (including excluded ones), maps, and
    /// sources checked on disk. Evidence export copies exactly these.
    #[serde(skip)]
    pub read_files: Vec<PathBuf>,
    /// Per source: what the initial scenario executed, for recommendations.
    #[serde(skip)]
    pub initial_execution: BTreeMap<String, InitialExecution>,
}

/// Initial-scenario bytes split into function execution and module evaluation.
#[derive(Debug, Default)]
pub struct InitialExecution {
    /// Bytes executed inside functions, or all observed bytes when the coverage format
    /// cannot separate them.
    pub function_bytes: usize,
    /// Generated code executed only at the script's top level.
    pub top_level: Vec<u8>,
}

/// Summary output keeps at most this many diagnostics per bundle; `--details` keeps all.
pub const SUMMARY_MAPPING_DIAGNOSTICS: usize = 100;

fn is_zero(value: &usize) -> bool {
    *value == 0
}

impl Report {
    fn limit_mapping_diagnostics(&mut self) {
        for bundle in &mut self.bundles {
            let total = bundle.mapping_diagnostics.len();
            if total <= SUMMARY_MAPPING_DIAGNOSTICS {
                continue;
            }
            bundle
                .mapping_diagnostics
                .truncate(SUMMARY_MAPPING_DIAGNOSTICS);
            bundle.omitted_mapping_diagnostics += total - SUMMARY_MAPPING_DIAGNOSTICS;
            for source in &mut bundle.sources {
                source
                    .mapping_diagnostics
                    .retain(|&index| index < SUMMARY_MAPPING_DIAGNOSTICS);
            }
            self.warnings.push(format!(
                "{}: summary lists the first {SUMMARY_MAPPING_DIAGNOSTICS} of {} mapping diagnostics; use --details for all",
                bundle.path, bundle.rejected_mappings
            ));
        }
        self.warnings.sort();
        self.warnings.dedup();
    }

    pub fn strip_details(&mut self) {
        self.limit_mapping_diagnostics();
        self.details = false;
        for bundle in &mut self.bundles {
            bundle.generated_source.clear();
            bundle.spans.clear();
            bundle.scenario_spans.clear();
            for source in &mut bundle.sources {
                source.content = None;
            }
        }
    }
}

pub fn sha256(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn javascript_files(dir: &Path, paths: &mut Vec<PathBuf>) -> Result<()> {
    for entry in fs::read_dir(dir).with_context(|| format!("read {}", dir.display()))? {
        let entry = entry?;
        let kind = entry.file_type()?;
        if kind.is_dir() {
            javascript_files(&entry.path(), paths)?;
        } else if kind.is_file()
            && matches!(
                entry.path().extension().and_then(|ext| ext.to_str()),
                Some("js" | "mjs" | "cjs")
            )
        {
            paths.push(entry.path());
        }
    }
    Ok(())
}

pub fn analyze(dir: &Path, coverage_files: &[PathBuf]) -> Result<Report> {
    analyze_with_options(dir, coverage_files, &AnalyzeOptions::default())
}

pub fn analyze_with_options(
    dir: &Path,
    coverage_files: &[PathBuf],
    options: &AnalyzeOptions,
) -> Result<Report> {
    let canonical_root = fs::canonicalize(dir)?;
    let input::Loaded {
        index: mut coverage,
        mut scenarios,
        warnings,
        recording_warnings,
    } = input::load(coverage_files, dir, &options.input)?;
    let mut profiles = cpu::Profiles::load(&options.profiles)?;
    let mut seen = BTreeSet::new();
    scenarios.retain(|name| seen.insert(name.clone()));
    if !options.scenario_order.is_empty() {
        ensure!(
            options.scenario_order.len() == scenarios.len()
                && options.scenario_order.iter().collect::<BTreeSet<_>>()
                    == scenarios.iter().collect(),
            "--scenario-order must list every scenario exactly once; received {:?}, recorded {scenarios:?}",
            options.scenario_order
        );
        scenarios.clone_from(&options.scenario_order);
    }
    if let Some(initial) = &options.initial_scenario {
        ensure!(
            scenarios.contains(initial),
            "unknown initial scenario {initial:?}; available scenarios: {scenarios:?}"
        );
        if options.scenario_order.is_empty() {
            scenarios.retain(|name| name != initial);
            scenarios.insert(0, initial.clone());
        } else {
            ensure!(
                scenarios.first() == Some(initial),
                "--initial-scenario must be first in --scenario-order"
            );
        }
    }
    let mut scenario_reports = scenarios
        .iter()
        .cloned()
        .map(scenario::Accumulator::new)
        .collect::<Vec<_>>();
    let mut files = Vec::new();
    if let Some(selected) = &options.files {
        for path in selected {
            coverage::validate_path(&path.to_string_lossy())?;
            let file = dir.join(path);
            ensure!(
                file.is_file(),
                "input file does not exist: {}",
                file.display()
            );
            ensure!(
                fs::canonicalize(&file)?.starts_with(fs::canonicalize(dir)?),
                "input file escapes analysis root: {}",
                file.display()
            );
            files.push(file);
        }
    } else {
        javascript_files(dir, &mut files)?;
    }
    files.sort();
    files.dedup();
    ensure!(
        !files.is_empty(),
        "no JavaScript files in {}",
        dir.display()
    );
    let mut report = Report {
        baseline: None,
        schema_version: 3,
        details: options.details,
        metric: "utf8-generated-source-bytes",
        attribution: "mapping-to-next-mapping-on-same-line; remaining bytes unmapped",
        scenarios,
        initial_scenario: options.initial_scenario.clone(),
        scenario_reports: Vec::new(),
        source_paths: "analysis-root-relative; virtual URL dot components removed",
        totals: Counts::default(),
        bundles: Vec::new(),
        sources: Vec::new(),
        packages: Vec::new(),
        warnings,
        recording_warnings,
        excluded_bundles: Vec::new(),
        include: options.include.clone(),
        exclude: options.exclude.clone(),
        compression: options.compression.then(ci::CompressedSizes::default),
        budget_failures: Vec::new(),
        compression_settings: options.compression.then_some("gzip level=6 (flate2 zlib-rs backend); Brotli quality=5 lgwin=22; independent whole files"),
        source_compression_method: options.source_compression.then_some("isolated attributed fragments in generated order per source per bundle; non-additive estimates, not measured transfer savings"),
        import_paths: None,
        recommendations: Vec::new(),
        cpu: None,
        label_generator: None,
        read_files: Vec::new(),
        initial_execution: BTreeMap::new(),
    };
    for path in options.maps.keys() {
        coverage::validate_path(path)?;
        ensure!(
            files.iter().any(|file| file
                .strip_prefix(dir)
                .is_ok_and(|p| p.to_string_lossy().replace('\\', "/") == *path)),
            "explicit map references file missing from selected inputs: {path}"
        );
    }
    let mut source_counts: BTreeMap<String, Counts> = BTreeMap::new();
    let include = ci::globs(&options.include)?;
    let exclude = ci::globs(&options.exclude)?;
    for file in files {
        let path = file.strip_prefix(dir)?.to_string_lossy().replace('\\', "/");
        report.read_files.push(file.clone());
        if (!options.include.is_empty() && !include.is_match(&path)) || exclude.is_match(&path) {
            coverage.remove(&path);
            profiles.exclude(&path);
            report.excluded_bundles.push(path);
            continue;
        }
        let content =
            fs::read_to_string(&file).with_context(|| format!("read UTF-8 source {path}"))?;
        let text = TextIndex::new(&content);
        let hash = sha256(content.as_bytes());
        let map_data = maps::load_with_location(&file, &content, dir, options.maps.get(&path))
            .with_context(|| format!("locate source map for {path}"))?;
        let source_map_path = map_data.as_ref().and_then(|map| map.path.clone());
        let (segments, map_hash, mut sources, rejected) = if let Some(map) = map_data {
            report.read_files.extend(map.path.clone());
            let attribution::IndexedAttribution {
                segments,
                rejected,
                sources,
            } = attribution::decode_indexed(
                &map.data,
                &text,
                content.len(),
                options.details,
                Some(&source_path::SourcePaths {
                    root: &canonical_root,
                    directory: &map.directory,
                }),
            )
            .with_context(|| format!("decode source map for {path}"))?;
            if !rejected.is_empty() {
                report.warnings.push(format!("{path}: ignored {} mapping points outside their line or inside a surrogate pair; attribution is approximate (see mappingDiagnostics)", rejected.len()));
            }
            (segments, Some(sha256(&map.data)), sources, rejected)
        } else {
            report
                .warnings
                .push(format!("{path}: no source map; entire source is unmapped"));
            (
                vec![IndexedSegment {
                    start: 0,
                    end: content.len(),
                    source: 0,
                    original: None,
                }],
                None,
                vec![IndexedSource {
                    name: UNMAPPED.into(),
                    content: None,
                }],
                Vec::new(),
            )
        };
        profiles.bind(&path, &hash, &map_hash, &text, &segments, &sources)?;
        let observations = coverage.remove(&path);
        let mut used = Vec::new();
        let mut scenario_used: BTreeMap<String, Vec<Interval>> = BTreeMap::new();
        let mut initial_function_used = Some((Vec::new(), Vec::new()));
        let mut verification = Vec::new();
        if let Some(observations) = &observations {
            for observation in observations {
                let binding = observation.verify(
                    &path,
                    &content,
                    &hash,
                    &map_hash,
                    options.input.allow_unverified,
                )?;
                if binding.source == "unverified" || binding.source_map == "unverified" {
                    report.warnings.push(format!("{path}: {} verification: source={}, source-map={}; current file hashes do not prove capture-time identity", observation.scenario, binding.source, binding.source_map));
                }
                verification.push(binding);
                if let input::Ranges::V8(functions) = &observation.ranges
                    && functions.iter().any(|function| {
                        !function.is_block_coverage
                            && function.ranges.iter().any(|range| range.count > 0)
                    })
                {
                    report.warnings.push(format!("{path}: executed function has function-only coverage; block detail unavailable"));
                }
                let ranges = observation
                    .used(&text)
                    .with_context(|| format!("normalize coverage for {path}"))?;
                if options.initial_scenario.as_ref() == Some(&observation.scenario) {
                    initial_function_used = match (
                        initial_function_used,
                        observation.function_used(&text, |root| {
                            // Bundler wrappers (webpack's runtime IIFE, module factories) map to no source.
                            // Turbopack factories and Rolldown's CommonJS wrappers have no mapping at their
                            // start, so the previous module's last mapping claims it, while the wrapper's
                            // own code maps to another source.
                            text.byte(root.start_offset).is_ok_and(|byte| {
                                let index = segments.partition_point(|s| s.end <= byte);
                                segments.get(index).is_some_and(|s| {
                                    s.source == 0
                                        || s.start < byte
                                            && text.byte(root.end_offset).is_ok_and(|end| {
                                                segments[index + 1..]
                                                    .iter()
                                                    .take_while(|next| next.start < end)
                                                    .find(|next| next.source != 0)
                                                    .is_some_and(|next| next.source != s.source)
                                            })
                                })
                            })
                        })?,
                    ) {
                        (Some((mut all, mut scopes)), Some((ranges, wrappers))) => {
                            all.extend(ranges);
                            scopes.extend(wrappers);
                            Some((all, scopes))
                        }
                        _ => None,
                    };
                }
                used.extend_from_slice(&ranges);
                scenario_used
                    .entry(observation.scenario.clone())
                    .or_default()
                    .extend(ranges);
            }
        }
        let used = coverage::union(used);
        let used_utf16 = used.iter().map(|range| range.end - range.start).sum();
        let used: Vec<Interval> = used
            .into_iter()
            .map(|range| {
                Ok(Interval {
                    start: text.byte(range.start)?,
                    end: text.byte(range.end)?,
                })
            })
            .collect::<Result<_>>()?;
        for ranges in scenario_used.values_mut() {
            *ranges = coverage::union(std::mem::take(ranges))
                .into_iter()
                .map(|range| {
                    Ok(Interval {
                        start: text.byte(range.start)?,
                        end: text.byte(range.end)?,
                    })
                })
                .collect::<Result<_>>()?;
        }
        if let Some(initial_used) = options
            .initial_scenario
            .as_ref()
            .and_then(|name| scenario_used.get(name))
        {
            let (function_used, mut boundaries) = match initial_function_used {
                Some((ranges, scopes)) => (
                    coverage::union(ranges)
                        .into_iter()
                        .map(|range| {
                            Ok(Interval {
                                start: text.byte(range.start)?,
                                end: text.byte(range.end)?,
                            })
                        })
                        .collect::<Result<Vec<_>>>()?,
                    scopes
                        .iter()
                        .flat_map(|scope| [scope.start, scope.end])
                        .map(|offset| text.byte(offset))
                        .collect::<Result<Vec<_>>>()?,
                ),
                None => (initial_used.clone(), Vec::new()),
            };
            boundaries.sort_unstable();
            let top_level = scenario::difference(initial_used, &function_used);
            let (mut function_cursor, mut top_level_cursor, mut boundary) = (0, 0, 0);
            for segment in &segments {
                // A mapping owns bytes up to the next mapping, which can run past a module
                // wrapper into the next module; those bytes are not this source's execution.
                while boundaries
                    .get(boundary)
                    .is_some_and(|&b| b <= segment.start)
                {
                    boundary += 1;
                }
                let segment = &IndexedSegment {
                    end: boundaries
                        .get(boundary)
                        .map_or(segment.end, |&b| b.min(segment.end)),
                    ..*segment
                };
                let function_bytes =
                    scenario::overlap(segment, &function_used, &mut function_cursor);
                scenario::overlap(segment, &top_level, &mut top_level_cursor);
                let ranges = top_level[top_level_cursor..]
                    .iter()
                    .take_while(|range| range.start < segment.end);
                if function_bytes == 0 && ranges.clone().next().is_none() {
                    continue;
                }
                let entry = report
                    .initial_execution
                    .entry(sources[segment.source].name.clone())
                    .or_default();
                entry.function_bytes += function_bytes;
                for range in ranges {
                    entry.top_level.extend_from_slice(
                        &content.as_bytes()
                            [range.start.max(segment.start)..range.end.min(segment.end)],
                    );
                }
            }
        }
        for scenario in &mut scenario_reports {
            scenario.bundle(
                &path,
                &segments,
                &sources,
                &scenario_used,
                options.initial_scenario.as_deref(),
                options.source_compression.then_some(content.as_bytes()),
            )?;
        }
        let phases =
            scenario::first_observed(&report.scenarios, &segments, sources.len(), &scenario_used);
        let estimates = if options.source_compression {
            let mut fragments = vec![Vec::new(); sources.len()];
            for segment in &segments {
                fragments[segment.source]
                    .extend_from_slice(&content.as_bytes()[segment.start..segment.end]);
            }
            fragments
                .iter()
                .map(|bytes| ci::compress(bytes).map(Some))
                .collect::<Result<Vec<_>>>()?
        } else {
            vec![None; sources.len()]
        };
        let mut counts = Counts::default();
        let mut mapped_bytes = 0;
        let mut used_index = 0;
        let mut bundle_sources: Vec<BundleSource> = Vec::new();
        let mut source_indices = vec![None; sources.len()];
        let mut spans = Vec::new();
        for segment in &segments {
            let source_index = if let Some(index) = source_indices[segment.source] {
                index
            } else {
                let source = &mut sources[segment.source];
                let index = bundle_sources.len();
                bundle_sources.push(BundleSource {
                    source: source.name.clone(),
                    package: attribution::package(&source.name),
                    content: source.content.take(),
                    first_observed: phases[segment.source].clone(),
                    estimated_compression: estimates[segment.source].clone(),
                    label: None,
                    rejected_mappings: 0,
                    mapping_diagnostics: Vec::new(),
                    counts: Counts::default(),
                });
                source_indices[segment.source] = Some(index);
                index
            };
            let bytes = segment.end - segment.start;
            while used_index < used.len() && used[used_index].end <= segment.start {
                used_index += 1;
            }
            let observed_bytes = used[used_index..]
                .iter()
                .take_while(|range| range.start < segment.end)
                .map(|range| {
                    range
                        .end
                        .min(segment.end)
                        .saturating_sub(range.start.max(segment.start))
                })
                .sum();
            let row = Counts {
                bytes,
                observed_bytes,
                unobserved_bytes: if observations.is_some() {
                    bytes - observed_bytes
                } else {
                    0
                },
                unmeasured_bytes: if observations.is_none() { bytes } else { 0 },
            };
            if segment.source != 0 {
                mapped_bytes += bytes;
            }
            bundle_sources[source_index].counts.add(&row);
            counts.add(&row);
            if options.details {
                let mut cursor = segment.start;
                let mut append = |start: usize, end: usize, status: Status| -> Result<()> {
                    if start < end {
                        spans.push(Span {
                            start,
                            end,
                            start_utf16: text.utf16(start)?,
                            end_utf16: text.utf16(end)?,
                            source: source_index,
                            status,
                            original: segment.original,
                        });
                    }
                    Ok(())
                };
                if observations.is_none() {
                    append(cursor, segment.end, Status::Unmeasured)?;
                } else {
                    for range in used[used_index..]
                        .iter()
                        .take_while(|r| r.start < segment.end)
                    {
                        let start = range.start.max(segment.start);
                        let end = range.end.min(segment.end);
                        append(cursor, start, Status::Unobserved)?;
                        append(start, end, Status::Observed)?;
                        cursor = end;
                    }
                    append(cursor, segment.end, Status::Unobserved)?;
                }
            }
        }
        ensure!(
            counts.bytes == content.len(),
            "{path}: source attribution lost bytes"
        );
        for source in &bundle_sources {
            source_counts
                .entry(source.source.clone())
                .or_default()
                .add(&source.counts);
        }
        let mut mapping_diagnostics = Vec::with_capacity(rejected.len());
        for (index, rejection) in rejected.iter().enumerate() {
            let (start, end) = (rejection.start, rejection.end);
            let overlapping = if start < end {
                &segments[segments.partition_point(|s| s.end <= start)
                    ..segments.partition_point(|s| s.start < end)]
            } else {
                &[]
            };
            let mut linked: Vec<usize> = overlapping
                .iter()
                .map(|s| s.source)
                .chain([rejection.mapping.source])
                .filter_map(|source| source_indices[source])
                .collect();
            linked.sort_unstable();
            linked.dedup();
            for source in linked {
                bundle_sources[source].rejected_mappings += 1;
                bundle_sources[source].mapping_diagnostics.push(index);
            }
            let describe = |mapping: &attribution::Mapping| MappingRef {
                generated_line: mapping.generated.0,
                generated_column: mapping.generated.1,
                source: sources[mapping.source].name.clone(),
                original: mapping.original,
            };
            mapping_diagnostics.push(MappingDiagnostic {
                reason: rejection.reason,
                mapping: describe(&rejection.mapping),
                previous: rejection.previous.as_ref().map(describe),
                next: rejection.next.as_ref().map(describe),
                inspect_region: Region {
                    start,
                    end,
                    start_utf16: text.utf16(start)?,
                    end_utf16: text.utf16(end)?,
                },
                assignments: overlapping
                    .iter()
                    .map(|s| Assignment {
                        start: s.start.max(start),
                        end: s.end.min(end),
                        source: sources[s.source].name.clone(),
                    })
                    .collect(),
            });
        }
        report.totals.add(&counts);
        let compression = if options.compression {
            Some(ci::compress(content.as_bytes())?)
        } else {
            None
        };
        if let (Some(total), Some(bundle)) = (&mut report.compression, &compression) {
            total.gzip_bytes += bundle.gzip_bytes;
            total.brotli_bytes += bundle.brotli_bytes;
        }
        report.bundles.push(BundleRow {
            path,
            sha256: hash,
            source_map_sha256: map_hash,
            utf16_units: text.utf16_len(),
            observed_utf16_units: observations.as_ref().map(|_| used_utf16),
            mapped_bytes,
            verification,
            generated_source: if options.details {
                content
            } else {
                String::new()
            },
            sources: bundle_sources,
            spans,
            scenario_spans: if options.details {
                report
                    .scenarios
                    .iter()
                    .map(|name| {
                        Ok((
                            name.clone(),
                            scenario::spans(
                                &segments,
                                scenario_used.get(name).map(Vec::as_slice),
                                &source_indices,
                                &text,
                            )?,
                        ))
                    })
                    .collect::<Result<_>>()?
            } else {
                BTreeMap::new()
            },
            compression,
            loading: None,
            rejected_mappings: rejected.len(),
            mapping_diagnostics,
            omitted_mapping_diagnostics: 0,
            counts,
            source_map_path,
        });
    }
    ensure!(
        !report.bundles.is_empty(),
        "no JavaScript files selected by --include/--exclude"
    );
    if options.files.is_some() && !coverage.is_empty() {
        let root = fs::canonicalize(dir)?;
        coverage.retain(|path, _| {
            let file = dir.join(path);
            // Keep missing/outside paths as errors: a wrong URL prefix must not
            // silently turn selected bundles into unmeasured code.
            if file.is_file() && fs::canonicalize(&file).is_ok_and(|file| file.starts_with(&root)) {
                report
                    .warnings
                    .push(format!("skipped coverage for unselected file: {path}"));
                false
            } else {
                true
            }
        });
    }
    ensure!(
        coverage.is_empty(),
        "coverage references files missing from analysis root {}: {:?}; check --dir, --url-prefix, or --script-map",
        dir.display(),
        coverage.keys().collect::<Vec<_>>()
    );
    // Like coverage: profiled files that exist but were not selected are skipped, missing ones fail.
    for path in profiles.pending() {
        let file = dir.join(&path);
        if options.files.is_some()
            && file.is_file()
            && fs::canonicalize(&file).is_ok_and(|file| file.starts_with(&canonical_root))
        {
            report
                .warnings
                .push(format!("skipped profile data for unselected file: {path}"));
            // Evidence export copies it, so a replay finds it unselected again.
            report.read_files.push(file);
            profiles.exclude(&path);
        }
    }
    let pending = profiles.pending();
    ensure!(
        pending.is_empty(),
        "profiles reference files missing from analysis root {}: {pending:?}; check --dir and the scenario prefix",
        dir.display()
    );
    report.cpu = profiles.finish()?;
    (report.sources, report.packages) = aggregate_sources(source_counts);
    let mut copies: BTreeMap<&str, (usize, usize)> = BTreeMap::new();
    for source in report.bundles.iter().flat_map(|bundle| &bundle.sources) {
        if source.source != UNMAPPED {
            let entry = copies.entry(&source.source).or_default();
            entry.0 += 1;
            entry.1 = entry.1.max(source.counts.bytes);
        }
    }
    let copies = copies
        .into_iter()
        .filter(|(_, (bundles, _))| *bundles > 1)
        .map(|(source, copies)| (source.to_owned(), copies))
        .collect::<BTreeMap<_, _>>();
    for source in &mut report.sources {
        if let Some(&(bundles, largest)) = copies.get(&source.source) {
            source.duplicates = Some(Duplicates {
                bundles,
                extra_bytes: source.counts.bytes - largest,
            });
        }
    }
    if options.source_compression {
        let mut estimates: BTreeMap<String, ci::CompressedSizes> = BTreeMap::new();
        let mut packages: BTreeMap<String, ci::CompressedSizes> = BTreeMap::new();
        for source in report.bundles.iter().flat_map(|bundle| &bundle.sources) {
            if let Some(estimate) = &source.estimated_compression {
                estimates
                    .entry(source.source.clone())
                    .or_default()
                    .add(estimate);
                packages
                    .entry(source.package.clone())
                    .or_default()
                    .add(estimate);
            }
        }
        for source in &mut report.sources {
            source.estimated_compression = estimates.remove(&source.source);
        }
        for package in &mut report.packages {
            package.estimated_compression = packages.remove(&package.package);
        }
    }
    report.scenario_reports = scenario_reports
        .into_iter()
        .map(scenario::Accumulator::finish)
        .collect();
    report.recommendations = recommendations::build(&report);
    if !options.details {
        report.limit_mapping_diagnostics();
    }
    report.warnings.sort();
    report.warnings.dedup();
    Ok(report)
}

fn aggregate_sources(source_counts: BTreeMap<String, Counts>) -> (Vec<SourceRow>, Vec<PackageRow>) {
    let mut sources = Vec::new();
    let mut packages: BTreeMap<String, Counts> = BTreeMap::new();
    for (source, counts) in source_counts {
        let package = attribution::package(&source);
        packages.entry(package.clone()).or_default().add(&counts);
        sources.push(SourceRow {
            source,
            package,
            estimated_compression: None,
            label: None,
            duplicates: None,
            counts,
        });
    }
    sources.sort_by(|a, b| {
        b.counts
            .bytes
            .cmp(&a.counts.bytes)
            .then(a.source.cmp(&b.source))
    });
    let mut packages: Vec<_> = packages
        .into_iter()
        .map(|(package, counts)| PackageRow {
            package,
            counts,
            estimated_compression: None,
        })
        .collect();
    packages.sort_by(|a, b| {
        b.counts
            .bytes
            .cmp(&a.counts.bytes)
            .then(a.package.cmp(&b.package))
    });
    (sources, packages)
}
