use std::collections::BTreeSet;
use std::fs;
use std::path::{Component, Path, PathBuf};

use anyhow::{Context, Result, ensure};
use clap::Parser;
use serde::{Deserialize, Serialize};

#[derive(Parser, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[command(
    version,
    about = "Trace generated JavaScript bytes to sources; import V8/DevTools coverage and export offline reports"
)]
struct Args {
    /// Analysis root; recursively scan JS files when no files/globs are supplied.
    #[arg(long, required_unless_present_any = ["inputs", "replay"])]
    dir: Option<PathBuf>,
    /// JavaScript files/globs relative to CWD; optionally an explicit .map after one file.
    #[arg(value_name = "FILE_OR_GLOB")]
    inputs: Vec<String>,
    /// Repeat for multiple scenarios. Observed ranges are unioned, not summed.
    #[arg(long)]
    coverage: Vec<PathBuf>,
    /// Initial scenario name for identifying bytes executed only during interactions.
    #[arg(long)]
    initial_scenario: Option<String>,
    /// First-observation order; comma-separated scenario names, each exactly once.
    #[arg(long, value_delimiter = ',')]
    scenario_order: Vec<String>,
    /// Estimate source gzip/Brotli sizes by compressing attributed fragments in isolation.
    #[arg(long)]
    source_compression: bool,
    /// Compare against a JSON report generated with the same analysis root convention.
    #[arg(long)]
    baseline: Option<PathBuf>,
    /// Fail when total generated-byte growth over --baseline exceeds this limit.
    #[arg(long, requires = "baseline")]
    max_added_bytes: Option<usize>,
    /// Limit unobserved-byte growth in --initial-scenario against the same baseline scenario.
    #[arg(long, requires_all = ["baseline", "initial_scenario"])]
    max_added_unobserved_bytes: Option<usize>,
    /// Optional esbuild metafile for import paths (not inferred from source maps).
    #[arg(long)]
    metafile: Option<PathBuf>,
    /// Build working directory used by esbuild metafile input keys (defaults to CWD).
    #[arg(long, requires = "metafile")]
    metafile_root: Option<PathBuf>,
    /// Bundler graph exported by the graph adapters (esbuild/webpack/Rollup/Vite/Turbopack).
    #[arg(long, conflicts_with = "metafile")]
    graph: Option<PathBuf>,
    /// Build/project root for graph source paths, defaults to CWD.
    #[arg(long, requires = "graph")]
    graph_root: Option<PathBuf>,
    /// Write source/bundle totals. Use --details to include code and ranges.
    #[arg(long)]
    json: Option<PathBuf>,
    /// Include code/ranges in JSON and an inline inspector in treemaps (can be large).
    #[arg(long)]
    details: bool,
    /// Write a self-contained interactive HTML report (includes source code).
    #[arg(long)]
    html: Option<PathBuf>,
    /// Write an interactive treemap; add --details for the code inspector.
    #[arg(long)]
    treemap: Option<PathBuf>,
    /// Write source totals as TSV. Use - for stdout with any output option.
    #[arg(long)]
    tsv: Option<PathBuf>,
    /// Strip this URL prefix to obtain an analysis-root-relative path. Repeatable; end with /.
    #[arg(long)]
    url_prefix: Vec<String>,
    /// JSON object mapping exact coverage URLs to relative bundle paths.
    #[arg(long)]
    script_map: Option<PathBuf>,
    /// Explicit bundle-relative-path=map-file binding. Repeatable; permits maps outside --dir.
    #[arg(long = "map")]
    maps: Vec<String>,
    /// Permit raw V8 inputs without captured source text/hash; mark them unverified.
    #[arg(long)]
    allow_unverified: bool,
    /// JSON config for include/exclude, compression, and budgets.
    #[arg(long)]
    config: Option<PathBuf>,
    /// Include bundle-relative glob (repeatable); * does not cross /.
    #[arg(long)]
    include: Vec<String>,
    /// Exclude bundle-relative glob (repeatable); takes precedence over include.
    #[arg(long)]
    exclude: Vec<String>,
    /// Calculate whole-file gzip (level 6) and Brotli (quality 5) sizes.
    #[arg(long)]
    compression: bool,
    /// Write a Markdown summary for CI artifacts.
    #[arg(long)]
    markdown: Option<PathBuf>,
    /// Fail with exit code 2 when selected generated bytes exceed this budget.
    #[arg(long)]
    max_bytes: Option<usize>,
    /// Fail when unobserved bytes exceed this budget. Does not include unmeasured bytes.
    #[arg(long)]
    max_unobserved_bytes: Option<usize>,
    /// Fail when unmeasured bytes exceed this budget.
    #[arg(long)]
    max_unmeasured_bytes: Option<usize>,
    /// Inferred source labels (from `coldpath label`), keyed by report source name.
    #[arg(long)]
    labels: Option<PathBuf>,
    /// Bundle load causes (from `coldpath snapshot`), keyed by bundle-relative path.
    #[arg(long)]
    loading: Option<PathBuf>,
    /// CPU profile from `coldpath profile`, bound to bundles by SHA-256. Repeat per scenario.
    #[arg(long)]
    #[serde(default)]
    profile: Vec<PathBuf>,
    /// Print the import chain and available locations for a graph input or report source.
    #[arg(long)]
    why: Option<String>,
    #[arg(long, default_value_t = 20)]
    limit: usize,
    /// Also copy every input this analysis read, with a manifest, into a new directory.
    #[arg(long, conflicts_with = "replay")]
    #[serde(skip)]
    export: Option<PathBuf>,
    /// Export only this bundle (bundle-relative path) or every bundle containing this
    /// report source, as an excerpt. Repeatable.
    #[arg(long, requires = "export")]
    #[serde(skip)]
    export_select: Vec<String>,
    /// Re-run an --export directory offline and compare with its recorded results.
    #[arg(long)]
    #[serde(skip)]
    replay: Option<PathBuf>,
    /// Directory that file:// coverage URLs were relative to at capture (set by --export).
    #[arg(long, hide = true)]
    file_url_root: Option<PathBuf>,
}

impl Args {
    /// Options that shape the analysis, without outputs or comparisons.
    fn analysis(&self) -> Result<serde_json::Value> {
        let mut args = self.clone();
        (args.json, args.html, args.treemap, args.tsv, args.markdown) =
            (None, None, None, None, None);
        (
            args.baseline,
            args.max_added_bytes,
            args.max_added_unobserved_bytes,
        ) = (None, None, None);
        (args.details, args.why, args.limit) = (false, None, 20);
        Ok(serde_json::to_value(args)?)
    }

    fn for_each_path(&mut self, mut f: impl FnMut(&Path) -> Result<PathBuf>) -> Result<()> {
        let mut apply = |path: &mut Option<PathBuf>| -> Result<()> {
            if let Some(value) = path {
                *value = f(value)?;
            }
            Ok(())
        };
        for path in [
            &mut self.dir,
            &mut self.metafile,
            &mut self.metafile_root,
            &mut self.graph,
            &mut self.graph_root,
            &mut self.script_map,
            &mut self.config,
            &mut self.labels,
            &mut self.loading,
        ] {
            apply(path)?;
        }
        for path in self.coverage.iter_mut().chain(&mut self.profile) {
            *path = f(path)?;
        }
        for input in &mut self.inputs {
            *input = f(Path::new(input))?.to_string_lossy().into_owned();
        }
        for binding in &mut self.maps {
            let (bundle, map) = binding
                .split_once('=')
                .context("--map must be bundle-relative-path=map-file")?;
            *binding = format!("{bundle}={}", f(Path::new(map))?.display());
        }
        Ok(())
    }
}

/// Recorded analysis options with paths resolved inside the evidence directory,
/// plus the output options given on the command line.
fn replay_args(cli: &Args, dir: &Path) -> Result<(Args, coldpath::evidence::Manifest)> {
    let bare = Args::parse_from(["coldpath", "--replay", "."]);
    ensure!(
        cli.analysis()? == bare.analysis()?,
        "--replay takes only output options (--json, --html, --treemap, --tsv, --markdown, --details, --limit)"
    );
    let manifest = coldpath::evidence::open(dir)?;
    let mut args: Args = serde_json::from_value(manifest.invocation.clone())
        .context("invalid evidence invocation")?;
    args.for_each_path(|path| {
        ensure!(
            path.components().all(|c| matches!(c, Component::Normal(_))),
            "unsafe evidence path {}",
            path.display()
        );
        Ok(dir.join(path))
    })?;
    (args.json, args.html, args.treemap, args.tsv, args.markdown) = (
        cli.json.clone(),
        cli.html.clone(),
        cli.treemap.clone(),
        cli.tsv.clone(),
        cli.markdown.clone(),
    );
    (args.details, args.limit, args.replay) = (cli.details, cli.limit, cli.replay.clone());
    Ok((args, manifest))
}

/// Copy what the analysis read, rewriting paths to evidence-relative ones.
fn export(
    out: &Path,
    args: &Args,
    root: &Path,
    selection: Option<&coldpath::selection::Selection>,
    input: &coldpath::input::InputOptions,
    report: &coldpath::Report,
) -> Result<()> {
    let mut selected = BTreeSet::new();
    for selector in &args.export_select {
        let matched = report
            .bundles
            .iter()
            .filter(|b| b.path == *selector || b.sources.iter().any(|s| s.source == *selector))
            .map(|b| b.path.clone())
            .collect::<Vec<_>>();
        ensure!(
            !matched.is_empty(),
            "--export-select {selector:?} {}",
            if report.excluded_bundles.contains(selector) {
                "is excluded from the analysis"
            } else {
                "matches no analyzed bundle or source"
            }
        );
        selected.extend(matched);
    }
    let excerpt = !selected.is_empty();
    let canonical =
        |path: &Path| fs::canonicalize(path).with_context(|| format!("resolve {}", path.display()));
    let root = canonical(root)?;
    let cwd = std::env::current_dir()?;
    let graph_root = args
        .graph
        .as_ref()
        .map(|_| canonical(args.graph_root.as_deref().unwrap_or(&cwd)))
        .transpose()?;
    let metafile_root = args
        .metafile
        .as_ref()
        .map(|_| canonical(args.metafile_root.as_deref().unwrap_or(&cwd)))
        .transpose()?;
    let read = report
        .read_files
        .iter()
        .map(|path| canonical(path))
        .collect::<Result<Vec<_>>>()?;
    let located = [&root]
        .into_iter()
        .chain(&read)
        .chain(&graph_root)
        .chain(&metafile_root)
        .cloned()
        .collect::<Vec<_>>();
    let mut writer = coldpath::evidence::Writer::new(out, &located)?;
    // An excerpt copies the selected bundles and their maps and lists everything else.
    let mut copied = BTreeSet::new();
    for bundle in report.bundles.iter().filter(|b| selected.contains(&b.path)) {
        copied.insert(canonical(&root.join(&bundle.path))?);
        copied.extend(
            bundle
                .source_map_path
                .iter()
                .map(|p| canonical(p))
                .collect::<Result<Vec<_>>>()?,
        );
    }
    let bundles = report
        .bundles
        .iter()
        .map(|b| &b.path)
        .chain(&report.excluded_bundles)
        .map(|path| canonical(&root.join(path)))
        .collect::<Result<BTreeSet<_>>>()?;
    let maps = report
        .bundles
        .iter()
        .filter_map(|b| b.source_map_path.as_deref())
        .map(canonical)
        .collect::<Result<BTreeSet<_>>>()?;
    for path in &read {
        if !excerpt || copied.contains(path) {
            writer.tree_file(path, "located")?;
        } else if bundles.contains(path) {
            writer.omit(path, "bundle")?;
        } else if maps.contains(path) {
            writer.omit(path, "map")?;
        } else {
            writer.omit(path, "located")?;
        }
    }
    let mut inv = args.clone();
    inv.file_url_root = Some(args.file_url_root.clone().unwrap_or(root.clone()));
    inv.dir = Some(writer.tree_dir(&root)?.into());
    // Import paths, labels, and load causes do not shape the bundle results an excerpt verifies.
    let (graph_root, metafile_root) = if excerpt {
        (None, None)
    } else {
        (graph_root, metafile_root)
    };
    inv.graph_root = graph_root
        .map(|p| writer.tree_dir(&p))
        .transpose()?
        .map(Into::into);
    inv.metafile_root = metafile_root
        .map(|p| writer.tree_dir(&p))
        .transpose()?
        .map(Into::into);
    // Positional globs become the literal files they selected; an excerpt lists its bundles.
    let keep = |bundle: &str| !excerpt || selected.contains(bundle);
    inv.inputs = match selection {
        Some(selection) => selection
            .files
            .iter()
            .filter(|file| keep(&file.to_string_lossy().replace('\\', "/")))
            .map(|file| root.join(file))
            .chain(
                selection
                    .maps
                    .iter()
                    .filter(|(bundle, _)| keep(bundle))
                    .map(|(_, map)| map.clone()),
            )
            .map(|path| writer.tree_file(&canonical(&path)?, "located"))
            .collect::<Result<_>>()?,
        None if excerpt => selected
            .iter()
            .map(|bundle| writer.tree_file(&canonical(&root.join(bundle))?, "located"))
            .collect::<Result<_>>()?,
        None => Vec::new(),
    };
    let mut maps = Vec::new();
    for binding in &args.maps {
        let (bundle, map) = binding.split_once('=').unwrap();
        let map = canonical(Path::new(map))?;
        if keep(bundle) {
            maps.push(format!("{bundle}={}", writer.tree_file(&map, "map")?));
        } else {
            writer.omit(&map, "map")?;
        }
    }
    inv.maps = maps;
    inv.coverage = args
        .coverage
        .iter()
        .map(|path| {
            if excerpt {
                let (data, removed) = coldpath::input::filter(path, &root, input, &selected)?;
                writer.derived(path, &data, "coverage", removed)
            } else {
                writer.input(path, "coverage")
            }
            .map(Into::into)
        })
        .collect::<Result<_>>()?;
    // Profiles do not shape the bundle results an excerpt verifies.
    inv.profile = Vec::new();
    for path in &args.profile {
        if excerpt {
            writer.omit(path, "profile")?;
        } else {
            inv.profile.push(writer.input(path, "profile")?.into());
        }
    }
    for (path, role, required) in [
        (&mut inv.script_map, "script-map", true),
        (&mut inv.config, "config", true),
        (&mut inv.metafile, "metafile", false),
        (&mut inv.graph, "graph", false),
        (&mut inv.labels, "labels", false),
        (&mut inv.loading, "loading", false),
    ] {
        if let Some(value) = path.take() {
            if excerpt && !required {
                writer.omit(&value, role)?;
            } else {
                *path = Some(writer.input(&value, role)?.into());
            }
        }
    }
    writer.finish(
        inv.analysis()?,
        report,
        excerpt.then(|| (args.export_select.clone(), selected)),
    )
}

fn main() -> Result<()> {
    let mut args = Args::parse();
    let replay = if let Some(dir) = args.replay.clone() {
        let (replayed, manifest) = replay_args(&args, &dir)?;
        args = replayed;
        Some(manifest)
    } else {
        None
    };
    let default_treemap = replay.is_none()
        && !args.inputs.is_empty()
        && args.json.is_none()
        && args.html.is_none()
        && args.treemap.is_none()
        && args.tsv.is_none()
        && args.markdown.is_none();
    if default_treemap {
        args.treemap = Some(PathBuf::from("coldpath.html"));
    }
    let stdout_count = [
        &args.json,
        &args.html,
        &args.treemap,
        &args.tsv,
        &args.markdown,
    ]
    .iter()
    .filter(|p| p.as_ref().is_some_and(|p| p.as_os_str() == "-"))
    .count();
    ensure!(
        stdout_count <= 1,
        "only one report may be written to stdout"
    );
    macro_rules! status { ($($arg:tt)*) => { if stdout_count > 0 { eprintln!($($arg)*); } else { println!($($arg)*); } }; }
    let selection = if args.inputs.is_empty() {
        None
    } else {
        Some(coldpath::selection::resolve(
            &args.inputs,
            args.dir.as_deref(),
        )?)
    };
    let dir = selection
        .as_ref()
        .map(|s| s.root.clone())
        .or(args.dir.clone())
        .unwrap();
    let mut config: coldpath::ci::Config = if let Some(path) = &args.config {
        serde_json::from_slice(&fs::read(path)?).context("invalid --config")?
    } else {
        Default::default()
    };
    let mut options = coldpath::AnalyzeOptions {
        initial_scenario: args.initial_scenario.clone(),
        scenario_order: args.scenario_order.clone(),
        source_compression: args.source_compression,
        include: config.include,
        exclude: config.exclude,
        // Retain sourcesContent temporarily to verify graph source snapshots and label evidence.
        // Evidence compares span boundaries, which only detailed analysis retains.
        details: args.details
            || args.export.is_some()
            || replay.is_some()
            || args.html.is_some()
            || args.graph.is_some()
            || args.labels.is_some(),
        profiles: args.profile.clone(),
        ..Default::default()
    };
    if let Some(selection) = &selection {
        options.files = Some(selection.files.clone());
        options.maps = selection.maps.clone();
    }
    options.include.extend(args.include.iter().cloned());
    options.exclude.extend(args.exclude.iter().cloned());
    options.compression = config.compression
        || args.compression
        || config.budgets.max_gzip_bytes.is_some()
        || config.budgets.max_brotli_bytes.is_some();
    config.budgets.max_bytes = args.max_bytes.or(config.budgets.max_bytes);
    config.budgets.max_unobserved_bytes = args
        .max_unobserved_bytes
        .or(config.budgets.max_unobserved_bytes);
    config.budgets.max_unmeasured_bytes = args
        .max_unmeasured_bytes
        .or(config.budgets.max_unmeasured_bytes);
    options.input.url_prefixes = args.url_prefix.clone();
    options.input.allow_unverified = args.allow_unverified;
    options.input.file_url_root = args.file_url_root.clone();
    if let Some(path) = &args.script_map {
        options.input.script_paths = serde_json::from_slice(&fs::read(path)?)
            .context("--script-map must be an object mapping URLs to relative paths")?;
    }
    for binding in &args.maps {
        let (bundle, map) = binding
            .split_once('=')
            .context("--map must be bundle-relative-path=map-file")?;
        ensure!(!map.is_empty(), "--map needs a map file path");
        ensure!(
            options.maps.insert(bundle.into(), map.into()).is_none(),
            "duplicate --map for {bundle}"
        );
    }
    let mut report = coldpath::analyze_with_options(&dir, &args.coverage, &options)?;
    if let Some(path) = &args.baseline {
        let comparison = coldpath::baseline::compare(&report, &fs::read(path)?)
            .with_context(|| format!("compare baseline {}", path.display()))?;
        report.warnings.extend(comparison.warnings.iter().cloned());
        report.baseline = Some(comparison);
    }
    report.budget_failures = config.budgets.check(&report);
    if let Some(limit) = args.max_added_unobserved_bytes {
        let name = report.initial_scenario.as_deref().unwrap();
        let comparison = report
            .baseline
            .as_ref()
            .unwrap()
            .scenarios
            .iter()
            .find(|row| row.scenario == name)
            .with_context(|| format!("baseline has no matching initial scenario {name:?}"))?;
        if comparison.totals.before.unmeasured_bytes != 0
            || comparison.totals.after.unmeasured_bytes != 0
        {
            report.budget_failures.push(format!("initial unobserved byte growth: cannot check while {name:?} has unmeasured bytes in either report"));
        } else if comparison.totals.delta.unobserved_bytes > limit as i128 {
            report.budget_failures.push(format!(
                "initial unobserved byte growth: {:+} exceeds budget {limit}",
                comparison.totals.delta.unobserved_bytes
            ));
        }
    }
    if let Some(limit) = args.max_added_bytes
        && let Some(comparison) = &report.baseline
        && comparison.totals.delta.bytes > limit as i128
    {
        report.budget_failures.push(format!(
            "generated byte growth: {:+} exceeds budget {limit}",
            comparison.totals.delta.bytes
        ));
    }
    if let Some(path) = &args.metafile {
        let mut paths = coldpath::metadata::import_paths(&fs::read(path)?)?;
        coldpath::metadata::bind_sources(
            &mut paths,
            &dir,
            &args
                .metafile_root
                .clone()
                .unwrap_or(std::env::current_dir()?),
        )?;
        report.import_paths = Some(paths);
    }
    if let Some(path) = &args.graph {
        coldpath::graph::attach(
            &mut report,
            &fs::read(path)?,
            &dir,
            &args.graph_root.clone().unwrap_or(std::env::current_dir()?),
        )?;
    }
    if let Some(path) = &args.labels {
        coldpath::annotations::attach_labels(&mut report, &fs::read(path)?)?;
    }
    if let Some(path) = &args.loading {
        coldpath::annotations::attach_loading(&mut report, &fs::read(path)?)?;
    }
    report.recommendations = coldpath::recommendations::build(&report);
    if let Some(out) = &args.export {
        export(
            out,
            &args,
            &dir,
            selection.as_ref(),
            &options.input,
            &report,
        )
        .with_context(|| format!("export evidence to {}", out.display()))?;
        status!("Wrote evidence {}", out.display());
    }
    let replay_exit = if let Some(manifest) = &replay {
        let differences = manifest
            .expected
            .differences(&coldpath::evidence::Expected::from_report(&report)?);
        for difference in &differences {
            eprintln!("replay differs: {difference}");
        }
        let current = coldpath::evidence::Analyzer::current();
        if manifest.analyzer != current {
            eprintln!(
                "replay used analyzer {} ({}); the evidence was recorded with {} ({}). Run that version to reproduce it exactly.",
                current.version,
                current.commit.as_deref().unwrap_or("unknown commit"),
                manifest.analyzer.version,
                manifest
                    .analyzer
                    .commit
                    .as_deref()
                    .unwrap_or("unknown commit"),
            );
            Some(3)
        } else if !differences.is_empty() {
            Some(1)
        } else if let Some(excerpt) = &manifest.excerpt {
            status!(
                "Replay verified an excerpt, not a complete reproduction: {} selected bundles reproduced their counts and spans; {} omitted inputs and the full-analysis totals were not checked.",
                excerpt.bundles.len(),
                excerpt.omitted.len()
            );
            Some(4)
        } else {
            status!("Replay reproduced every recorded result.");
            None
        }
    } else {
        None
    };
    ensure!(
        args.why.is_none() || report.import_paths.is_some(),
        "--why requires --graph or --metafile"
    );
    status!(
        "Generated UTF-8 bytes: {} ({} bundles)",
        report.totals.bytes,
        report.bundles.len()
    );
    status!(
        "Observed: {} | Unobserved: {} | Unmeasured: {}",
        report.totals.observed_bytes,
        report.totals.unobserved_bytes,
        report.totals.unmeasured_bytes
    );
    status!("Unobserved means not executed during the supplied scenarios, not safe to delete.\n");
    if let Some(comparison) = &report.baseline {
        status!(
            "Change from baseline: {:+} generated bytes",
            comparison.totals.delta.bytes
        );
        for row in comparison
            .sources
            .iter()
            .filter(|row| row.change != "unchanged")
            .take(args.limit)
        {
            status!("{:+12}  {} ({})", row.delta.bytes, row.name, row.change);
        }
        if let Some(cpu) = &comparison.cpu {
            let count = |change: &str| {
                cpu.sources
                    .iter()
                    .filter(|row| row.change == change)
                    .count()
            };
            status!(
                "CPU change from baseline: {} regressed | {} improved | {} unchanged | {} inconclusive",
                count("regressed"),
                count("improved"),
                count("unchanged"),
                count("inconclusive")
            );
            for row in cpu
                .sources
                .iter()
                .filter(|row| matches!(row.change, "regressed" | "improved"))
                .take(args.limit)
            {
                status!(
                    "{:+12.2} ms  {} ({}, {} window, {})",
                    row.shift_us.unwrap_or_default() / 1000.0,
                    row.source,
                    row.scenario,
                    row.window,
                    row.change
                );
            }
        }
    }
    for scenario in &report.scenario_reports {
        status!(
            "Scenario {}: {} observed | {} unobserved | {} unmeasured",
            scenario.scenario,
            scenario.totals.observed_bytes,
            scenario.totals.unobserved_bytes,
            scenario.totals.unmeasured_bytes
        );
    }
    if !report.excluded_bundles.is_empty() {
        status!(
            "{} bundles excluded; totals and budgets use selected bundles only.\n",
            report.excluded_bundles.len()
        );
    }
    if let Some(compression) = &report.compression {
        status!(
            "Whole-file compression sum: gzip {} B | Brotli {} B\n",
            compression.gzip_bytes,
            compression.brotli_bytes
        );
    }
    status!(
        "{:>12} {:>12} {:>12} {:>12}  Package",
        "Bytes",
        "Observed",
        "Unobserved",
        "Unmeasured"
    );
    let mut packages = report.packages.iter().collect::<Vec<_>>();
    if !args.coverage.is_empty() {
        packages.sort_by(|a, b| {
            b.counts
                .unobserved_bytes
                .cmp(&a.counts.unobserved_bytes)
                .then(a.package.cmp(&b.package))
        });
    }
    for row in packages.into_iter().take(args.limit) {
        status!(
            "{:>12} {:>12} {:>12} {:>12}  {}",
            row.counts.bytes,
            row.counts.observed_bytes,
            row.counts.unobserved_bytes,
            row.counts.unmeasured_bytes,
            row.package
        );
    }
    if let Some(source) = &args.why {
        let row = report
            .import_paths
            .as_ref()
            .unwrap()
            .iter()
            .find(|row| row.source == *source || row.resolved_source.as_ref() == Some(source))
            .ok_or_else(|| anyhow::anyhow!("no matched graph input {source}"))?;
        status!(
            "\nImport path ({} graph): {}",
            row.graph_format,
            row.path
                .as_ref()
                .map(|path| path.join(" -> "))
                .unwrap_or("[unknown]".into())
        );
        for edge in &row.edges {
            let location = edge
                .location
                .as_ref()
                .map(|l| format!(":{}:{}", l.line, l.column))
                .unwrap_or_default();
            status!(
                "  {}{} --{:?}--> {}",
                edge.from,
                location,
                edge.kind,
                edge.to
            );
        }
    }
    for warning in &report.warnings {
        eprintln!("warning: {warning}");
    }
    if let Some(path) = args.html {
        write_report(path, coldpath::report::html(&report)?)?;
    }
    if let Some(path) = args.treemap {
        write_report(
            path.clone(),
            coldpath::report::treemap_with_inspector(&report, args.details)?,
        )?;
        if default_treemap {
            status!("Wrote {}", path.display());
        }
    }
    if let Some(path) = args.tsv {
        write_report(path, coldpath::report::tsv(&report))?;
    }
    if !args.details {
        report.strip_details();
    }
    if let Some(path) = args.json {
        write_report(path, serde_json::to_string(&report)? + "\n")?;
    }
    if let Some(path) = args.markdown {
        write_report(path, coldpath::ci::markdown(&report))?;
    }
    if let Some(code) = replay_exit {
        std::process::exit(code);
    }
    if replay.is_none() && !report.budget_failures.is_empty() {
        for failure in &report.budget_failures {
            eprintln!("budget failed: {failure}");
        }
        std::process::exit(2);
    }
    Ok(())
}

fn write_report(path: PathBuf, content: String) -> Result<()> {
    if path.as_os_str() == "-" {
        use std::io::Write;
        std::io::stdout().lock().write_all(content.as_bytes())?;
        return Ok(());
    }
    if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}
